language: objective-c
osx_image: xcode9
env:
    global:
    - PROJECT=NxEnabled.xcodeproj
    - IOS_FRAMEWORK_SCHEME="NxEnabled iOS"
    matrix:
    - DESTINATION="platform=iOS Simulator,OS=11.0,name=iPhone 6"

script:
    - set -o pipefail
    - xcodebuild test -project "$PROJECT" -scheme "$IOS_FRAMEWORK_SCHEME" -destination "$DESTINATION" | xcpretty -c --test --color

after_success:
    - sleep 5 # workaround https://github.com/travis-ci/travis-ci/issues/4725
